## Numpy array basic


In [43]:
import numpy as np

### creating array from list


In [44]:
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array: ", arr1d)

arr2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
print("1D Array: ", arr2d)

1D Array:  [1 2 3 4 5]
1D Array:  [[1 2 3 4 5]
 [6 7 8 9 0]]


### List vs numpy array


In [45]:
list = [1, 2, 3]
print("Python list Multiplication ", list * 2)

np_array = np.array([1, 2, 3])  # element wise multiplication
print("Python array Multiplication ", np_array * 2)


import time

start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation time", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time", time.time() - start)

Python list Multiplication  [1, 2, 3, 1, 2, 3]
Python array Multiplication  [2 4 6]

 List operation time 0.056439876556396484

 Numpy operation time 0.004367828369140625


## creating array from scratch


In [46]:
zeros = np.zeros((4, 4))
print("\n", zeros)

ones = np.ones((3, 3))
print("\n", ones)

full = np.full((3, 4), 7)
print("\nFull array \n", full)

# random = np.random.random((2, 3))
# print('Random array\n', random)

sequence = np.arange(0, 11, 3)
print(sequence, end="")


 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full array 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[0 3 6 9]

## Vector, Matrix, Tensor


In [47]:
# 1D array (vector)
vector = np.array([1, 2, 3])
print(f"Vector \n {vector}")

# 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix \n{matrix}")

# 3D array (tensor)
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor", tensor)

Vector 
 [1 2 3]
Matrix 
[[1 2 3]
 [4 5 6]]
Tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Data Type", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Data Type int64


### Array Reshaping

In [49]:
arr = np.arange(12)  # non-exclusive in range
print("Original Array", arr)

reShaped = arr.reshape((3, 4))
print("Reshaped array\n", reShaped)

flattend = reShaped.flatten()
print('Flatend array', flattend)

# ravel (return view, instead of copy)
raveled = reShaped.ravel()
print('Raveled array', raveled)

# Transpose Matrix
transpose = reShaped.T
print('Transpose array\n', transpose)

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatend array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
